 <?php
    $this->headLink()->appendStylesheet('css/default.css')
                     ->appendStylesheet('css/w3css.css')
                     ->appendStylesheet('css/jquery.mobile-1.4.5.css');
    
//    $this->headScript()->prependFile('scripts/jquery.mobile-1.4.5.min.js');
  ?>


<script>
        function myFunction(x) {
            x.classList.toggle("change");
            
            if($('#menuContainer').is(':visible')){
                $('#menuContainer').slideUp( 400, function() {
                    // Animation complete.
                  });
            }else{
                $('#menuContainer').slideDown( 400, function() {
                    // Animation complete.
                  });
            }
        }
    </script>
    
    
<table data-role="table" data-mode="columntoggle" class="ui-responsive" id="myTable">
  <thead>
    <tr class="headerRow" >
      <th data-priority="6">CustomerID</th>
      <th>CustomerName</th>
      <th data-priority="1">ContactName</th>
      <th data-priority="2">Address</th>
      <th data-priority="3">City</th>
      <th data-priority="4">PostalCode</th>
      <th data-priority="5">Country</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>1</td>
      <td>Alfreds Futterkiste</td>
      <td>Maria Anders</td>
      <td>Obere Str. 57</td>
      <td>Berlin</td>
      <td>12209</td>
      <td>Germany</td>
    </tr>
    <tr>
      <td>1</td>
      <td>Alfreds Futterkiste</td>
      <td>Maria Anders</td>
      <td>Obere Str. 57</td>
      <td>Berlin</td>
      <td>12209</td>
      <td>Germany</td>
    </tr>
    <tr>
      <td>1</td>
      <td>Alfreds Futterkiste</td>
      <td>Maria Anders</td>
      <td>Obere Str. 57</td>
      <td>Berlin</td>
      <td>12209</td>
      <td>Germany</td>
    </tr>
    <tr>
      <td>1</td>
      <td>Alfreds Futterkiste</td>
      <td>Maria Anders</td>
      <td>Obere Str. 57</td>
      <td>Berlin</td>
      <td>12209</td>
      <td>Germany</td>
    </tr>
  </tbody>
</table>