<div id="LoginForm">
    <div class="w3-row">
        <div class="w3-col l12 s12 w3-center"><input type="text" class="user" placeholder='User name'></p></div>
        <div class="w3-col l12 s12 w3-center"><input type="text" class="password" placeholder='Password'></div>
        <div class="w3-col l12 s12 w3-center login"><p><a href="/login/login">Login</a></p></div>
        <div class="w3-col l12 s12 w3-center"><p><a href="/login/create" onclick="generalClick(this)">No Account? Create one here!</a></p></div>
    </div>
</div>
