<html xmlns="http://www.w3.org/1999/xhtml">
    
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>BitBudget</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="https://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
</head>
    
    
    <?php
    $this->headLink()->prependStylesheet('/css/default.css')
                     ->prependStylesheet('/css/w3css.css')
                     ->prependStylesheet('/css/jquery.mobile-1.4.5.css');

    echo $this->doctype();
    echo $this->headLink();
    
    
    $this->headScript()->prependFile('/scripts/window.js');
    
    echo $this->headScript();
?>

    
<body>    
    <div id="container">
        <div id="headerContainer">
            <div id="header">
                
                <div class="iconContainer" onclick="openMenu(this)">
                    <div class="bar1"></div>
                    <div class="bar2"></div>
                    <div class="bar3"></div>
                </div>
                
                <div id="header-logo">
                    <a href="/" onclick="generalClick(this)">
                        <b id="bit">Bit</b>
                        <b id="budget">Budget</b>
                    </a>
                </div>
                
                <div id="loginLogo">
                    <a href="/login" onclick="logOut()">
                        <i class="fa fa-lock"></i>
                    </a>
                </div>
            </div>
        </div>

        <div id="menuContainer">
            <div id="menu">
                <div class="w3-row">
                    <div class="w3-col l3 s12 home w3-center"><p><a href="/">Home</a></p></div>
                    <div class="w3-col l3 s12 entry w3-center"><p><a href="/entry">Entry</a></p></div>
                    <div class="w3-col l3 s12 accounts w3-center"><p><a href="/accounts">Accounts</a></p></div>
                    <div class="w3-col l3 s12 reports   w3-center"><p><a href="/reports">Reports</a></p></div>
                </div>
            </div>
        </div>
        <div id="subNavigation">
            <a href="/<?php  echo Zend_Controller_Front::getInstance()->getRequest()->getControllerName()?>" onclick="generalClick(this)">
                <?php
                    if(Zend_Controller_Front::getInstance()->getRequest()->getControllerName() != "index"){
                    echo strtoupper(Zend_Controller_Front::getInstance()->getRequest()->getControllerName());
                    }else{
                        echo "HOME";
                    }
                ?>
            </a>
            
            <?php
            if(Zend_Controller_Front::getInstance()->getRequest()->getActionName() != "index"){
            ?>
            /
            <a href="/<?php echo Zend_Controller_Front::getInstance()->getRequest()->getControllerName();?>/<?php echo Zend_Controller_Front::getInstance()->getRequest()->getActionName()?>" onclick="generalClick(this)">
                <?php
                    echo strtoupper(Zend_Controller_Front::getInstance()->getRequest()->getActionName());
                ?>
            </a>
            <?php
            }
            ?>
        </div>


        <div id="content">
            <?php 
                echo $this->layout()->content;
            ?>
        </div>
        
        <div id="footer">
            <footer class="w3-container">
                <h5>Footer</h5>
            </footer>
        </div>
    </div>

    
 
</body>
    
</html>